# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NxqtbdreKJMpxC1HSAZ1Ov69uleMje3w
"""

!pip -q install openpyxl

import pandas as pd
import numpy as np
import re

from google.colab import files
from IPython.display import display

print("Libraries are ready")

print("Select an Excel file")

uploaded = files.upload()

file_name = next(iter(uploaded))

print(f"File uploaded successfully: {file_name}")

excel_file = pd.ExcelFile(file_name)

sheet_names = excel_file.sheet_names

print(f"Number of sheets: {len(sheet_names)}")
print()

for i, sheet in enumerate(sheet_names, 1):
    print(f"{i}. {sheet}")

def clean_column_name(col):
    col = str(col).strip()
    col = re.sub(r'\s+', '_', col)
    col = re.sub(r'[^\w\u0600-\u06FF]', '_', col)
    col = re.sub(r'_+', '_', col)
    col = col.strip('_')

    if not col:
        col = "Unnamed_Column"

    return col

print("Column cleaning function created")

cleaned_sheets = {}
summary = []

for sheet in sheet_names:

    print(f"Cleaning: {sheet}")

    df = pd.read_excel(file_name, sheet_name=sheet)

    original_rows = len(df)
    original_cols = len(df.columns)

    # Clean column names
    df.columns = [clean_column_name(c) for c in df.columns]

    # Handle duplicate column names
    new_columns = []
    used_columns = {}

    for col in df.columns:

        if col not in used_columns:
            used_columns[col] = 0
            new_columns.append(col)

        else:
            used_columns[col] += 1
            new_columns.append(
                f"{col}_{used_columns[col]}"
            )

    df.columns = new_columns

    # Remove completely empty columns
    df = df.dropna(axis=1, how='all')

    # Remove completely empty rows
    df = df.dropna(axis=0, how='all')

    # Clean text values
    for col in df.select_dtypes(include=['object']).columns:

        df[col] = (
            df[col]
            .astype("string")
            .str.strip()
        )

        df[col] = df[col].replace({
            "": pd.NA,
            "nan": pd.NA,
            "None": pd.NA,
            "NaN": pd.NA
        })

    # Count duplicates
    duplicates = int(df.duplicated().sum())

    # Remove duplicate rows
    df = df.drop_duplicates()

    # Try to convert date columns
    for col in df.columns:

        col_name = str(col).lower()

        if any(
            x in col_name
            for x in [
                'date',
                'time',
                'datetime',
                'created',
                'updated'
            ]
        ):

            try:
                converted = pd.to_datetime(
                    df[col],
                    errors='coerce'
                )

                valid_ratio = (
                    converted.notna().mean()
                    if len(df) > 0
                    else 0
                )

                if valid_ratio >= 0.70:
                    df[col] = converted

            except Exception:
                pass

    cleaned_sheets[sheet] = df

    summary.append({
        "Sheet": sheet,
        "Original Rows": original_rows,
        "Clean Rows": len(df),
        "Original Columns": original_cols,
        "Clean Columns": len(df.columns),
        "Duplicates Removed": duplicates,
        "Missing Values": int(df.isna().sum().sum())
    })

    print(
        f"Completed: {original_rows:,} rows -> "
        f"{len(df):,} rows | "
        f"{original_cols} columns -> "
        f"{len(df.columns)} columns"
    )

print()
print("All sheets have been cleaned successfully")

summary_df = pd.DataFrame(summary)

print("CLEANING SUMMARY")

display(summary_df)

data_dictionary = []

for sheet, df in cleaned_sheets.items():

    for col in df.columns:

        data_dictionary.append({
            "Sheet": sheet,
            "Column": col,
            "Data Type": str(df[col].dtype),
            "Rows": len(df),
            "Missing Values": int(df[col].isna().sum()),
            "Missing %": round(
                df[col].isna().mean() * 100,
                2
            ),
            "Unique Values": int(
                df[col].nunique(dropna=True)
            )
        })

dictionary_df = pd.DataFrame(data_dictionary)

print("DATA DICTIONARY")

display(dictionary_df)

output_file = "PowerBI_Extract_Cleaned.xlsx"

with pd.ExcelWriter(
    output_file,
    engine="openpyxl"
) as writer:

    summary_df.to_excel(
        writer,
        sheet_name="Cleaning_Summary",
        index=False
    )

    dictionary_df.to_excel(
        writer,
        sheet_name="Data_Dictionary",
        index=False
    )

    used_sheet_names = set()

    for sheet, df in cleaned_sheets.items():

        safe_sheet_name = str(sheet)[:31]

        base_name = safe_sheet_name
        counter = 1

        while safe_sheet_name in used_sheet_names:

            suffix = f"_{counter}"

            safe_sheet_name = (
                base_name[:31 - len(suffix)]
                + suffix
            )

            counter += 1

        used_sheet_names.add(safe_sheet_name)

        df.to_excel(
            writer,
            sheet_name=safe_sheet_name,
            index=False
        )

print("Excel file created successfully:")
print(output_file)

print("PREVIEW OF CLEANED DATA")

for sheet, df in cleaned_sheets.items():

    print()
    print("-" * 70)
    print(sheet)
    print("-" * 70)

    display(df.head(10))

print()
print("Downloading the file...")

files.download(output_file)

print()
print("Execution completed successfully")